name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up JDK 25
        uses: actions/setup-java@v5.5.0
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven (including static analysis)
        run: mvn clean verify -P check

      - name: Upload test reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-reports
          path: '**/target/surefire-reports/'
          retention-days: 7

      - name: Upload static analysis reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: static-analysis-reports
          path: '**/target/code-analysis/'
          retention-days: 7
